### ISSUE TITLE
	Illegal request

### ISSUE THREAD

**Issue by DeyV** [javanile/vtiger#12]
Docker, 7.1 , latest, 17.09.2019 , on https by traefic in public domain

Almost every form generate error : 

`Illegal request` (bo back)
 
for example: 
index.php?module=Users&view=PreferenceDetail&parent=Settings&record=1
index.php?module=Profiles&parent=Settings&view=Edit&record=3

only errors I've found in logs: 

```
[Tue Sep 17 09:08:45.253978 2019] [ssl:warn] [pid 23] AH01906: localhost:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Sep 17 09:08:45.254352 2019] [ssl:warn] [pid 23] AH01909: localhost:443:0 server certificate does NOT include an ID which matches the server name

```

**Comment by francescobianco** [comment]
Try to set the following environment variable:
VT_SITE_URL=https://crm.mydomain.com

**Comment by DeyV** [comment]
thx, it's works. 

Can You add this information to docker page and repo with demo?
