### ISSUE TITLE
Add custom location to .symvol

### ISSUE THREAD

**Issue by spatialy** [javanile/vtiger#33]
Hi, how we can add custom locations to .symbol for persistence?

We have tried adding /modules and /layouts but this is not added when the container is recreated.

Best

Yulian

**Comment by francescobianco** [comment]
Hi @spatialy it is easy:

Create a custom `Dockerfile` and a custom `.symbol` with the following

```Dockerfile
FROM javanile/vtiger:7.1.0
COPY .symbol-custom /var/www/html/.symbol
```
copy all lines of original `.symvol` https://github.com/javanile/vtiger/blob/master/7.1.0/.symvol into the custom one

than build your docker file with

```bash
docker build -t custom/vtiger:7.1.0 .
```

**Comment by spatialy** [comment]
Sorry for the delayed response ... work perfect, big thanks!
