### ISSUE TITLE
php 7.*

### ISSUE THREAD

**Issue by DeyV** [javanile/vtiger#4]
vTiger support php 5.6 and 7.

But PHP 5.6 End of Life happened on December 31, 2018.

7.0 is not supported by PHP team too,
So ... maybe it's good time to check docker with 7.1 or even 7.2

**Comment by valentt** [comment]
I had Vtiger install on DigitalOcen with php 7.2 and it worked great, I would suggest that you test and release php 7.x version if it works also for you.

**Comment by francescobianco** [comment]
Tested version with PHP 7.2 was released. Thanks for your supports.
Keep up to date with changes with this link https://github.com/javanile/vtiger#php-versions

**Comment by DeyV** [comment]
thx
